controller_list:
  - name: fake_first_manipulator_controller
    joints:
      - 1_sia5d_joint_s
      - 1_sia5d_joint_l
      - 1_sia5d_joint_e
      - 1_sia5d_joint_u
      - 1_sia5d_joint_r
      - 1_sia5d_joint_b
      - 1_sia5d_joint_t
  - name: fake_second_manipulator_controller
    joints:
      - 2_sia5d_joint_s
      - 2_sia5d_joint_l
      - 2_sia5d_joint_e
      - 2_sia5d_joint_u
      - 2_sia5d_joint_r
      - 2_sia5d_joint_b
      - 2_sia5d_joint_t
  - name: fake_dual_manipulator_controller
    joints:
      - 1_sia5d_joint_s
      - 1_sia5d_joint_l
      - 1_sia5d_joint_e
      - 1_sia5d_joint_u
      - 1_sia5d_joint_r
      - 1_sia5d_joint_b
      - 1_sia5d_joint_t
      - 2_sia5d_joint_s
      - 2_sia5d_joint_l
      - 2_sia5d_joint_e
      - 2_sia5d_joint_u
      - 2_sia5d_joint_r
      - 2_sia5d_joint_b
      - 2_sia5d_joint_t